version: 2

sources:
  - name: raw_cricket
    tables:
      - name: leagues
        meta:
          external_location: "'../../data/stageddata/leagues.parquet'"
      - name: teams
        meta:
          external_location: "'../../data/stageddata/teams.parquet'"
      - name: leagues
        meta:
          external_location: "'../../data/stageddata/leagues.parquet'"
      - name: deliveries
        meta:
          external_location: "'../../data/stageddata/deliveries/*/*.parquet'"
      - name: matches
        meta:
          external_location: "'../../data/stageddata/matches/*/*.parquet'"
      - name: players
        meta:
          external_location: "'../../data/stageddata/players.parquet'"